
services:
  wazoo-web-server:
    container_name: webserver
    build: .
    ports:
      - "80:8080"
    depends_on:
      - mongo-server
    networks:
      - main-network

  mongo-server:
    image: mongo:5.0
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: wazoo
      MONGO_INITDB_ROOT_PASSWORD: wazoo1234
    ports:
      - "27017:27017"
    networks:
      - main-network


networks:
  main-network:
