spring:
  datasource:
    url: jdbc:mysql://localhost:3306/picnicdb
    username: root
    password: 31215
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG